version: "3.9"

services:
  web:
    build: .
    network_mode: "host"
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
